import React from "react";
import Head from "next/head";
import Image from "next/image";

import Header from "../components/header";
import Footer from "../components/footer";
import HeroImage from "../public/images/image7.png";
import Image1 from "../public/images/image8.png";
import Image2 from "../public/images/image9.png";
import Image3 from "../public/images/image10.png";
import Image4 from "../public/images/image11.png";
import team1 from "../public/images/team1.png";
import team2 from "../public/images/team2.png";
import team3 from "../public/images/team3.png";
import team4 from "../public/images/team4.png";
import styles from "../styles/aboutus.module.css";

function AboutUs(props) {
  return (
    <div>
      <Head>
        <title>About us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <div className={" " + styles.hero_section} >
        <Image src={HeroImage} layout="fill" />
        <div
          className={
            "container h-full  mx-auto flex flex-col  justify-center " +
            styles.heroText
          }
        >
          <p className=" uppercase font-semibold">About us</p>
          <h2 className=" uppercase text-5xl font-bold">
            Serving the world around us
          </h2>
        </div>
      </div>
      <div
        className={"container mx-auto text-center mt-12 " + styles.main_text}
      >
        <div>
          <p className=" uppercase">Welcome to our MOSQUE</p>
          <h1 className=" text-5xl font-bold uppercase  mb-6">
            Love and compassion
          </h1>
          <p className=" w-2/3  mx-auto">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
            ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
            aliquip ex ea commodo consequat. Duis aute irure dolor in
            reprehenderit in voluptate velit esse cillum.
          </p>

          <div className="grid grid-cols-3 grid-flow-row gap-4  my-10">
            <div className="w-full h-full flex items-center justify-end">
              <img
                src="images/a-bearded-man-praying-5206040.png"
                className=" float-right"
              />
            </div>
            <div className="mx-auto">
              <img
                src="images/man-and-woman-reading-book-while-sitting-on-pews-8468470.png"
                className="mx-auto "
              />
            </div>
            <div className="w-full h-full flex items-center justify-start">
              <img src="images/people-sitting-on-brown-pews-8674151.png" />
            </div>
          </div>
        </div>

        <div className="grid grid-cols-2 grid-flow-row gap-4 mx-auto text-left w-2/3">
          <div>
            <p className=" uppercase"> OUR MISSIOn & Vision</p>
            <h3 className=" text-3xl font-bold uppercase my-4">
              STRIVING FOR A BETTER TOMORROW
            </h3>
            <p className=" text-sm text-justify">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
              enim ad minim veniam, quis nostrud exercitation ullamco laboris
              nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
              reprehenderit in voluptate velit esse cillum.
            </p>
          </div>
          <div>
            <p className=" uppercase"> WHAT WE DO</p>
            <h3 className=" text-3xl font-bold uppercase my-4">
              BRINgING PEACE AND JOY TO THE WORLD
            </h3>
            <p className=" text-sm text-justify">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
              enim ad minim veniam, quis nostrud exercitation ullamco laboris
              nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
              reprehenderit in voluptate velit esse cillum.
            </p>
          </div>
        </div>

        <div className="text-center mt-28 mb-6">
          <p className=" uppercase">BENEFITS</p>
          <h2 className=" uppercase text-4xl font-bold">
            THE benefits of <br />
            joining our mosque
          </h2>
        </div>

        <div className="grid grid-cols-2 grid-flow-row gap-8 text-justify my-12">
          <div className="flex  flex-col justify-center">
            <h3 className=" uppercase font-bold text-2xl">
              find fulfillment and joy
            </h3>
            <p className="mt-4">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
              enim ad minim veniam, quis nostrud exercitation ullamco laboris
              nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
              reprehenderit.
            </p>
          </div>
          <div>
            <div className=" relative  h-96">
              <Image src={Image1} layout="fill" />
            </div>
          </div>
        </div>

        <div className="grid grid-cols-2 grid-flow-row gap-8 text-justify my-12">
          <div className=" relative  h-96">
            <Image src={Image2} layout="fill" />
          </div>

          <div className="flex  flex-col justify-center">
            <h3 className=" uppercase font-bold text-2xl">shared values</h3>
            <p className="mt-4">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
              enim ad minim veniam, quis nostrud exercitation ullamco laboris
              nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
              reprehenderit.
            </p>
          </div>
        </div>

        <div className="grid grid-cols-2 grid-flow-row gap-8 text-justify my-12">
          <div className="flex  flex-col justify-center">
            <h3 className=" uppercase font-bold text-2xl">charity events</h3>
            <p className="mt-4">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
              enim ad minim veniam, quis nostrud exercitation ullamco laboris
              nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
              reprehenderit.
            </p>
          </div>
          <div>
            <div className=" relative  h-96">
              <Image src={Image3} layout="fill" />
            </div>
          </div>
        </div>

        <div className="grid grid-cols-2 grid-flow-row gap-8 text-justify my-12">
          <div className=" relative  h-96">
            <Image src={Image4} layout="fill" />
          </div>

          <div className="flex  flex-col justify-center">
            <h3 className=" uppercase font-bold text-2xl">All are welcome</h3>
            <p className="mt-4">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
              enim ad minim veniam, quis nostrud exercitation ullamco laboris
              nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
              reprehenderit.
            </p>
          </div>
        </div>

        <div className={"mt-12" + styles.team_members}>
          <p className=" uppercase">mosque members</p>
          <h2 className=" uppercase text-4xl font-bold mb-12">
            meet our Inspirational team
          </h2>
          <div className=" grid grid-cols-4 grid-flow-col gap-4">
            <div
              className={
                "bg_grey flex flex-col justify-center " + styles.team_card
              }
            >
              <div className=" w-2/3    relative mx-auto">
                <Image src={team2} width={150} height={150} />
              </div>
              <p className=" font-bold uppercase">Kim Bowen</p>
              <p className=" text-sm   text-[#161722]">Hassan, Mosque</p>
              <span className="flex justify-center mt-5">
                <img src="images/icons/black_fb.svg" />
                <img src="images/icons/black_twitter.svg" className="mx-5" />
                <img src="images/icons/black_linkedin.svg" />
              </span>
            </div>

            <div
              className={
                "bg_grey flex flex-col justify-center " + styles.team_card
              }
            >
              <div className=" w-2/3    relative mx-auto">
                <Image src={team1} width={150} height={150} />
              </div>
              <p className=" font-bold uppercase">Danielle Watkins</p>
              <p className=" text-sm   text-[#161722]">Hassan, Mosque</p>
              <span className="flex justify-center mt-5">
                <img src="images/icons/black_fb.svg" />
                <img src="images/icons/black_twitter.svg" className="mx-5" />
                <img src="images/icons/black_linkedin.svg" />
              </span>
            </div>

            <div
              className={
                "bg_grey flex flex-col justify-center " + styles.team_card
              }
            >
              <div className=" w-2/3    relative mx-auto">
                <Image src={team3} width={150} height={150} />
              </div>
              <p className=" font-bold uppercase">Naomi Craig</p>
              <p className=" text-sm   text-[#161722]">Hassan, Mosque</p>
              <span className="flex justify-center mt-5">
                <img src="images/icons/black_fb.svg" />
                <img src="images/icons/black_twitter.svg" className="mx-5" />
                <img src="images/icons/black_linkedin.svg" />
              </span>
            </div>

            <div
              className={
                "bg_grey flex flex-col justify-center " + styles.team_card
              }
            >
              <div className=" w-2/3    relative mx-auto">
                <Image src={team4} width={150} height={150} />
              </div>
              <p className=" font-bold uppercase">Santos Payne</p>
              <p className=" text-sm   text-[#161722]">Hassan, Mosque</p>
              <span className="flex justify-center mt-5">
                <img src="images/icons/black_fb.svg" />
                <img src="images/icons/black_twitter.svg" className="mx-5" />
                <img src="images/icons/black_linkedin.svg" />
              </span>
            </div>
             
          </div>
        </div>
      </div>
      <Footer />
    </div>
  );
}

export default AboutUs;
