import React from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import Header from "../components/header";
import Footer from "../components/footer";
import image1 from "../public/images/image13.png";

import styles from "../styles/blog.module.css";
import StylishCard from "../components/utility/stylishCard";
function blog(props) {
  return (
    <div style={{ background: "#F5F2F0" }}>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <p className=" uppercase text-center mt-24">OUR BLOG</p>
      <h2 className=" font-bold text-5xl uppercase text-center mb-12">
        most recent post
      </h2>
      <div className={"container mx-auto p-6  " + styles.recent_post}>
        <div className="grid grid-flow-row grid-cols-2 gap-4  h-full">
          <div className=" relative h-full">
            <Image src={image1} layout="fill" />
          </div>
          <div>
            <div className="flex justify-between uppercase">
              <p>Tuesday 13 May, 2022</p>
              <p>By John Hunau Deo</p>
            </div>
            <h2 className=" text-3xl uppercase font-bold mt-5">
              Church was doing what he often did when dropped An oracle
            </h2>
            <p className=" text-justify mt-4">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
              enim ad minim veniam, quis nostrud exercitation ullamco laboris
              nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor.
            </p>
            <Link href={"/blog-post"}>
              <button className="btn_primary uppercase mt-10">Read more</button>
            </Link>
          </div>
        </div>
      </div>

      <div className="container mx-auto">
        <h2 className=" uppercase text-5xl text-center font-bold my-28">
          ALL BLOG POSTS
        </h2>
        <div className="grid grid-cols-4 grid-flow-row gap-4">
        <StylishCard
            orangeText="Relationship"
            bg_color="bg-white"
            heading="HOW TO SHOW COMPASSION"
            name="By Mathew Johnson"
            dateTime="Tuesday 13 May, 2021"
            date="20 july"
          >
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua.
          </StylishCard>
          <StylishCard
            orangeText="Relationship"
            bg_color="bg-white"
            heading="HOW TO SHOW COMPASSION"
            name="By Mathew Johnson"
            dateTime="Tuesday 13 May, 2021"
            date="20 july"
          >
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua.
          </StylishCard>

          <StylishCard
            orangeText="Relationship"
            bg_color="bg-white"
            heading=" THE BIBLICAL PURPOSE OF MONEY"
            name="By Mathew Johnson"
            dateTime="Tuesday 13 May, 2021"
            date="20 july"
          >
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua.
          </StylishCard>
          <StylishCard
            orangeText="Relationship"
            bg_color="bg-white"
            heading=" THE BIBLICAL PURPOSE OF MONEY"
            name="By Mathew Johnson"
            dateTime="Tuesday 13 May, 2021"
            date="20 july"
          >
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua.
          </StylishCard>
          <StylishCard
            orangeText="Relationship"
            bg_color="bg-white"
            heading=" WATCH AND LISTEN TO OUR SERMONS"
            name="By Mathew Johnson"
            dateTime="Tuesday 13 May, 2021"
            date="20 july"
          >
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua.
          </StylishCard>

          <StylishCard
            orangeText="Relationship"
            bg_color="bg-white"
            heading=" WATCH AND LISTEN TO OUR SERMONS"
            name="By Mathew Johnson"
            dateTime="Tuesday 13 May, 2021"
            date="20 july"
          >
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua.
          </StylishCard>
          <StylishCard
            orangeText="Relationship"
            bg_color="bg-white"
            heading=" WATCH AND LISTEN TO OUR SERMONS"
            name="By Mathew Johnson"
            dateTime="Tuesday 13 May, 2021"
            date="20 july"
          >
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua.
          </StylishCard>
        </div>
      </div>
      <Footer />
    </div>
  );
}

export default blog;
