import React from "react";
import Head from "next/head";
import Image from "next/image";

import Header from "../components/header";
import Footer from "../components/footer";
import image1 from "../public/images/image14.png";
import image2 from "../public/images/image15.png";
import StylishDiv from "../components/utility/stylishTextDiv";

function BlogPost(props) {
  return (
    <div style={{ background: "#F5F2F0" }}>
      <Head>
        <title>blog post</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="uppercase text-center mt-32 mb-12">
        <p className="  orange_text  "> Relationship</p>
        <h2 className=" uppercase font-bold   text-5xl">
          HOW TO SHOW COMPASSION
        </h2>
        <p className="mt-6">13 May, 2018 By Mathew Johnson</p>
      </div>
      <div className=" container mx-auto">
        <div className=" relative   " style={{ height: "500px" }}>
          <Image src={image1} layout="fill" />
        </div>
        <div className=" mt-12 text-center  w-3/4 mx-auto">
          <h3 className=" uppercase font-bold text-5xl text-justify">
            LOREM IPSUM DOLOR SIT AMET
          </h3>
          <p className=" text-justify mt-6 text-lg">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
            ad minim veniam, quis nostrud exercitation. Ullamco laboris nisi ut
            aliquip ex ea commodo consequat. Duis aute irure dolor in
            reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
            pariatur. Non tellus orci ac auctor augue mauris augue neque
            gravida.
          </p>
          <p className=" text-justify mt-6 text-lg">
            Aenean vel elit scelerisque mauris. Imperdiet sed euismod nisi porta
            lorem mollis aliquam. Quis vel eros donec ac odio tempor orci
            dapibus ultrices. Elementum eu facilisis sed odio morbi. Nam at
            lectus urna duis convallis convallis tellus id. Feugiat pretium nibh
            ipsum consequat nisl vel. Elementum pulvinar etiam non quam lacus.
            Sit amet porttitor eget.
          </p>
          <div className=" relative my-16" style={{ height: "500px" }}>
            <Image src={image2} layout="fill" />
          </div>
          <h3 className=" uppercase font-bold text-3xl my-10 text-justify">
            LOREM IPSUM DOLOR SIT AMET
          </h3>

          <p className=" text-justify mt-6 text-lg  ">
            Aenean vel elit scelerisque mauris. Imperdiet sed euismod nisi porta
            lorem mollis aliquam. Quis vel eros donec ac odio tempor orci
            dapibus ultrices. Elementum eu facilisis sed odio morbi. Nam at
            lectus urna duis convallis convallis tellus id. Feugiat pretium nibh
            ipsum consequat nisl vel. Elementum pulvinar etiam non quam lacus.
            Sit amet porttitor eget.
          </p>

          <StylishDiv>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua. Dui
            faucibus in ornare quam viverra orci sagittis eu volutpat.
          </StylishDiv>

          <p className=" text-justify mt-6 text-lg  ">
            Aenean vel elit scelerisque mauris. Imperdiet sed euismod nisi porta
            lorem mollis aliquam. Quis vel eros donec ac odio tempor orci
            dapibus ultrices. Elementum eu facilisis sed odio morbi. Nam at
            lectus urna duis convallis convallis tellus id. Feugiat pretium nibh
            ipsum consequat nisl vel. Elementum pulvinar etiam non quam lacus.
            Sit amet porttitor eget.
          </p>

          <h3 className=" uppercase font-bold text-3xl my-10 text-justify">
            LOREM IPSUM DOLOR SIT AMET CONSECTETUR
          </h3>

          <p className=" text-justify mt-6 text-lg  ">
            Aenean vel elit scelerisque mauris. Imperdiet sed euismod nisi porta
            lorem mollis aliquam. Quis vel eros donec ac odio tempor orci
            dapibus ultrices. Elementum eu facilisis sed odio morbi. Nam at
            lectus urna duis convallis convallis tellus id. Feugiat pretium nibh
            ipsum consequat nisl vel. Elementum pulvinar etiam non quam lacus.
            Sit amet porttitor eget.
          </p>
          <ul className="text-justify my-12 list-inside list-disc">
            <li className="">
              Lorem ipsum dolor sit amet, consectetur adipiscing
            </li>
            <li>Purus sit amet luctus venenatis lectus magna</li>
            <li>Aenean vel elit scelerisque mauris. Imperdiet sed euismod</li>
          </ul>

          <p className=" text-justify mt-6 text-lg  ">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
            ad minim veniam, quis nostrud exercitation. Ullamco laboris nisi ut
            aliquip ex ea commodo consequat. Duis aute irure dolor in
            reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
            pariatur. Non tellus orci ac auctor augue mauris augue neque
            gravida.
          </p>

          <p className=" text-justify mt-6 text-lg  ">
            Saepe magni aut maxime vel voluptatem. Ab eveniet neque placeat qui
            porro ab minus voluptas. Dicta praesentium neque vero mollitia
            aperiam sed enim. Lacinia quis vel eros donec ac odio.
          </p>
        </div>
      </div>
      <Footer />
    </div>
  );
}

export default BlogPost;
