import React from "react";
import Head from "next/head";
import Image from "next/image";
import Header from "../components/header";
import Footer from "../components/footer";
import image1 from "../public/images/image17.png";

import styles from "../styles/aboutus.module.css";

function contact(props) {
  return (
    <div style={{ background: "#F5F2F0" }}>
      <Head>
        <title>Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className={"  relative "} style={{ height: "75vh" }}>
        <Image src={image1} layout="fill" className=" absolute" />
        <div
          className={
            "container h-full  mx-auto flex flex-col  justify-center relative " +
            styles.heroText
          }
        >
          <p className=" uppercase font-semibold text-[#FFD2A4] my-3">
            CONTACT
          </p>
          <h2 className=" uppercase text-5xl font-bold text-white">
            Get in touch with <br />
            our MOSQUE
          </h2>
        </div>
      </div>

      <div className="container mx-auto mt-24">
      <h3 className=" uppercase text-2xl font-bold">Contact form:</h3>
        <div className="grid grid-cols-2 grid-flow-row gap-20">
          <div>
          
            <input
              type={"text"}
              className="w-full p-3 bg-white rounded mt-6"
              placeholder="Your full Name"
            />
            <input
              type={"email"}
              className="w-full p-3 bg-white rounded my-3"
              placeholder="Your Email"
            />

            <input
              type={"text"}
              className="w-full p-3 bg-white rounded"
              placeholder="Query Related"
            />
            <textarea
              rows={"6"}
              className=" w-full bg-white my-3 p-3 rounded"
              placeholder="Message"
            />
             <button className=" btn_primary uppercase w-full text-center justify-center">send message</button>
          </div>
          <div>
            <p className=" text-gray-500 mt-6">Address</p>
            <h4 className=" uppercase font-bold">
              NH 234 Public Square
              <br />
              San Francisco 65368
            </h4>

            <p className=" text-gray-500 mt-6">Contact Details</p>
            <h4 className=" uppercase font-bold">
              (480) 555-0103
              <br />
              finsweet@example.com
            </h4>

            <p className=" text-gray-500 mt-6">Find us here</p>
            <span className="flex    mt-1">
                <img src="images/icons/black_fb.svg" />
                <img src="images/icons/black_twitter.svg" className="mx-5" />
                <img src="images/icons/black_linkedin.svg" />
              </span>
             
          </div>
        </div>
      </div>
      <Footer />
    </div>
  );
}

export default contact;
