import Head from "next/head";
import Image from "next/image";

import Header from "../components/header";
import Footer from "../components/footer";
import MainImage from "../public/images/mian_image.png";
import Image1 from "../public/images/image1.png";
import Image2 from "../public/images/image2.png";
import Image3 from "../public/images/image3.png";
import Image4 from "../public/images/image4.png";
import Image5 from "../public/images/image5.png";
import Image6 from "../public/images/image6.png";
import styles from "../styles/index.module.css";
import StylishCard from "../components/utility/stylishCard";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <div className={styles.main_image_div + " text-white"}>
        <Image src={MainImage} layout="fill" />
        <div className={"container mx-auto    " + styles.main_text}>
          <div className={""}>
            <p>Welcome to our MOSQUE</p>
            <h1 className=" text-6xl font-bold uppercase ">Become a part of</h1>
            <h1 className=" text-6xl font-bold uppercase mt-4">
              our community{" "}
            </h1>
            <button className=" uppercase btn_primary my-12">learn more</button>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do.
            </p>
          </div>
        </div>
      </div>
      <div className={ styles.sub_section}>
        <h1 className=" text-5xl font-bold mt-32 text-center uppercase mb-11">
          a mosque that<span>&apos;</span>s relevant
        </h1>
        <div className="container mx-auto">
          <div className="grid grid-cols-3 grid-flow-row gap-4">
            <div
              className={
                styles.card +
                " bg_light_orange rounded-sm flex flex-col items-center justify-center"
              }
            >
              <div className=" w-72 body_text">
                <Image src={"images/icons/pray.svg"} className=" " layout="fill"/>
                <h1 className=" text-3xl uppercase font-bold my-3">about us</h1>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
                  do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                </p>
              </div>
              <div className={"card_footer " + styles.card_footer}> </div>
            </div>

            <div
              className={
                styles.card +
                " bg_light_orange rounded-sm flex flex-col items-center justify-center"
              }
            >
              <div className=" w-72 body_text">
                <Image src={"images/icons/heart.svg"} className=" " layout="fill"/>
                <h1 className=" text-3xl uppercase font-bold my-3">
                  Get involved
                </h1>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
                  do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                </p>
              </div>
              <div className={"card_footer " + styles.card_footer}> </div>
            </div>
            <div
              className={
                styles.card +
                " bg_light_orange rounded-sm flex flex-col items-center justify-center"
              }
            >
              <div className=" w-72 body_text">
                <img src={"images/icons/share.svg"} className=" " />
                <h1 className=" text-3xl uppercase font-bold my-3">
                  Giving back
                </h1>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
                  do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                </p>
              </div>
              <div className={"card_footer " + styles.card_footer}> </div>
            </div>
          </div>
        </div>
      </div>

      <div className={"container mx-auto   " + styles.sub_section}>
        <h1 className=" text-5xl font-bold mt-32 text-center uppercase mb-11">
          a mosque that<span>&apos;</span>s relevant
        </h1>
        <p className=" w-3/4 mx-auto text-center">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
          minim veniam, quis nostrud exercitation ullamco laboris nisi ut
          aliquip ex ea commodo consequat. Duis aute irure dolor in
          reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
          pariatur.
        </p>
        <div className="container mx-auto">
          <div className="grid grid-cols-3 grid-flow-row gap-4">
            <div>
              <img
                src="images/a-bearded-man-praying-5206040.png"
                className=" float-right"
              />
            </div>
            <div className="mx-auto">
              <button className="btn_primary mx-auto my-8 uppercase">
                Read more
              </button>
              <img
                src="images/man-and-woman-reading-book-while-sitting-on-pews-8468470.png"
                className="mx-auto "
              />
            </div>
            <div>
              <img src="images/people-sitting-on-brown-pews-8674151.png" />
            </div>
          </div>
        </div>
      </div>

      <div className="my-10 container mx-auto text-center">
        <p>our mission & vision</p>
        <h3 className=" uppercase font-bold text-3xl">celebrate WITH US</h3>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua.
        </p>
        <p className="mt-3">Read More &#8594;</p>
      </div>

      <div>
        <div className={" text-center " + styles.benefits_section}>
          <p className=" uppercase">Watch and listen</p>
          <h1 className=" text-5xl font-bold uppercase mt-3 mb-6">
            THE benefits of
            <br /> joining our church
          </h1>

          <div className={"container mx-auto mt-4"}>
            <div className="grid grid-cols-4 grid-flow-row gap-4">
              <div className={" " + styles.benefits_card}>
                <Image src={Image1} layout="fill" className=" absolute" />
                <div className={"" + styles.shadow_overly}></div>
                <div
                  className={
                    " text-white flex flex-col items-center justify-center pl-4 pr-4 " +
                    styles.benefits_overlay_text
                  }
                >
                  <h1 className=" uppercase text-2xl mb-3">
                    WATCH AND LISTEN TO OUR SERMONS
                  </h1>
                  <p className="mb-3">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
                    do eiusmod tempor incididunt ut.
                  </p>
                </div>
              </div>
              <div className={" " + styles.benefits_card}>
                <Image src={Image2} layout="fill" className=" absolute" />
                <div className={"" + styles.shadow_overly}></div>
                <div
                  className={
                    " text-white flex flex-col items-center justify-center pl-4 pr-4 " +
                    styles.benefits_overlay_text
                  }
                >
                  <h1 className=" uppercase text-2xl mb-3">
                    WATCH AND LISTEN TO OUR SERMONS
                  </h1>
                  <p className="mb-3">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
                    do eiusmod tempor incididunt ut.
                  </p>
                </div>
              </div>
              <div className={" " + styles.benefits_card}>
                <Image src={Image3} layout="fill" className=" absolute" />
                <div className={"" + styles.shadow_overly}></div>
                <div
                  className={
                    " text-white flex flex-col items-center justify-center pl-4 pr-4 " +
                    styles.benefits_overlay_text
                  }
                >
                  <h1 className=" uppercase text-2xl mb-3">
                    WATCH AND LISTEN TO OUR SERMONS
                  </h1>
                  <p className="mb-3">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
                    do eiusmod tempor incididunt ut.
                  </p>
                </div>
              </div>
              <div className={" " + styles.benefits_card}>
                <Image src={Image4} layout="fill" className=" absolute" />
                <div className={"" + styles.shadow_overly}></div>
                <div
                  className={
                    " text-white flex flex-col items-center justify-center pl-4 pr-4 " +
                    styles.benefits_overlay_text
                  }
                >
                  <h1 className=" uppercase text-2xl mb-3">
                    WATCH AND LISTEN TO OUR SERMONS
                  </h1>
                  <p className="mb-3">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
                    do eiusmod tempor incididunt ut.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className={"container text-center mx-auto mt-32 "}>
        <p className=" uppercase "> Upcoming SERMONS</p>
        <h1 className="text-5xl font-bold uppercase mb-4">
          join us and become part <br />
          of something great
        </h1>
        <div
          className={"grid grid-cols-3 grid-flow-row gap-0 " + styles.register}
        >
          <div className="bg_light_orange p-4 text-left flex flex-col   justify-center">
            <p className="flex justify-between uppercase ">
              <span></span>
              <span>
                <span className="font-bold">20</span>
                <br />
                July
              </span>
            </p>
            <div className="ml-10 w-80 ">
              <p className=" uppercase clear-both text-sm orange_text">
                Upcoming Event
              </p>
              <h4 className=" uppercase font-bold text-2xl mb-3">
                WATCH AND LISTEN TO OUR SERMONS
              </h4>
              <p className="text-sm">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor.
              </p>
              <p className="mt-2 flex ">
                <img src="images/icons/clock.svg" className="mr-4" /> Friday
                23:39 IST <br />
                Saturday 11:20 ISD
              </p>
              <p className="mt-2 flex ">
                <img src="images/icons/location.svg" className="mr-4"  /> No 233
                Main St. New York,
                <br /> United States
              </p>
              <button className=" uppercase btn_secondry mt-3">Register</button>
            </div>
          </div>
          <div className="col-span-2">
            <div className="  relative  h-full">
              <Image src={Image5} layout="fill" />
            </div>
          </div>
        </div>
        <p className=" float-right my-4">View all Sermons &#8594;</p>
      </div>
      <div className={"mt-32 clear-both " + styles.visit}>
        <Image src={Image6} layout="fill" className={styles.visit_img} />
        <div className={styles.overlay_img}></div>

        <div
          className={
            styles.cta +
            " bg-white rounded flex flex-col items-center justify-center mx-auto"
          }
        >
          <div
            className={
              "grid grid-cols-2 grid-flow-row gap-4 " + styles.body_text
            }
          >
            <div>
              <h2 className=" uppercase text-5xl font-bold">
                We want to
                <br /> serve the world <br /> around us
              </h2>
              <p className="my-10">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do.
              </p>
              <button className="btn_primary uppercase">Visit</button>
            </div>

            <div className="flex flex-col items-center justify-center">
              < img src="images/icons/quote_icons.svg"   />
            </div>
          </div>
          <div className={"  " + styles.bottom_color}></div>
        </div>
      </div>

      <div className="container mt-32 mx-auto">
        <p className="text-center uppercase">Read our Blog</p>
        <h1 className=" uppercase text-5xl font-bold text-center mt-4 mb-16">
          SHARE, INSPIRE, INNOVATE
        </h1>
        <div className="grid grid-cols-4 grid-flow-row gap-4">
          <StylishCard
            orangeText="Relationship"
            bg_color="bg_light_orange"
            heading=" WATCH AND LISTEN TO OUR SERMONS"
            name="By Mathew Johnson"
            dateTime="Tuesday 13 May, 2021"
          >
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua.
          </StylishCard>

          <StylishCard
            orangeText="Relationship"
            bg_color="bg_light_orange"
            heading=" WATCH AND LISTEN TO OUR SERMONS"
            name="By Mathew Johnson"
            dateTime="Tuesday 13 May, 2021"
          >
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua.
          </StylishCard>

          <StylishCard
            orangeText="Relationship"
            bg_color="bg_light_orange"
            heading=" WATCH AND LISTEN TO OUR SERMONS"
            name="By Mathew Johnson"
            dateTime="Tuesday 13 May, 2021"
          >
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua.
          </StylishCard>

          <StylishCard
            orangeText="Relationship"
            bg_color="bg_light_orange"
            heading=" WATCH AND LISTEN TO OUR SERMONS"
            name="By Mathew Johnson"
            dateTime="Tuesday 13 May, 2021"
          >
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua.
          </StylishCard>
        </div>
      </div>
      <br />
      <Footer />
    </div>
  );
}
